name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v3
        id: pages_conf
        with:
          enablement: true
          token: ${{ secrets.GH_PAT }}

      - name: Build app
        run: npm run build
        env:
          BASE_SITE_URL: ${{ steps.pages_conf.outputs.base_path }}

      - name: Archive artifact
        shell: sh
        run: |
          chmod -c -R +rX "$INPUT_PATH" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ runner.temp }}/artifact.tar

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GH_PAT }}
          artifact_name: artifact
