name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Authenticate SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_REPO_TOKEN }}

      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DEPLOY_REPO }}
          ref: main
          path: deploy-repo

      - name: Delete old build files
        run: rm -rf deploy-repo/*

      - name: Copy build files to target repository
        run: cp -R dist/* deploy-repo

      - name: Get repo name
        env:
          REPO_URL: ${{ secrets.DEPLOY_REPO }}
        id: repo_url
        run: echo "::set-output name=repo_name::${REPO_URL##*/}"

      - name: Commit and push changes to target repository
        uses: EndBug/add-and-commit@v9
        with:
          message: Update build ${{ github.run_number }}
          add: "."
          push: true
          cwd: "deploy-repo"
        env:
          BASE_SITE_URL: /${{ steps.repo_url.outputs.repo_name }}/
