name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DEPLOY_REPO }}
          ref: main
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: deploy-repo

      - name: Delete old build files
        run: rm -rf deploy-repo/*

      - name: Copy build files to target repository
        run: cp -R dist/* deploy-repo

      - name: Commit and push changes to target repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update build"
          add: "."
          push: true
          directory: "deploy-repo"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
