name: Lighthouse CI
on:
  workflow_run:
    workflows:
      - Build and Deploy
    types:
      - completed
    branches:
      - main

  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        id: pages_conf
        with:
          enablement: true
          token: ${{ secrets.GH_PAT }}

      - name: Audit Resume using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        id: lighthouse
        with:
          urls: ${{ steps.pages_conf.outputs.base_url }}/
          temporaryPublicStorage: true
          runs: 3

      - name: Calculate total score
        id: score
        env:
          REPORT_JSON: ${{ steps.lighthouse.outputs.manifest }}
        run: |
          performance=$(python -c "import json; data = json.loads(${REPORT_JSON@Q}); print(round(data[2]['summary']['performance']*100))")
          accessibility=$(python -c "import json; data = json.loads(${REPORT_JSON@Q}); print(round(data[2]['summary']['accessibility']*100))")
          bestPractices=$(python -c "import json; data = json.loads(${REPORT_JSON@Q}); print(round(data[2]['summary']['best-practices']*100))")
          seo=$(python -c "import json; data = json.loads(${REPORT_JSON@Q}); print(round(data[2]['summary']['seo']*100))")
          pwa=$(python -c "import json; data = json.loads(${REPORT_JSON@Q}); print(round(data[2]['summary']['pwa']*100))")
          scores="$performance $accessibility $bestPractices $seo $pwa"
          echo "result=\"$scores\""
          echo "result=$scores" >> $GITHUB_OUTPUT

      - name: Add summary
        env:
          LINKS_JSON: ${{ steps.lighthouse.outputs.links }}
        run: |
          report_url=$(python -c "import json; data = json.loads(${LINKS_JSON@Q}); print(list(data.values())[0])")
          echo "## Lighthouse Report" >> $GITHUB_STEP_SUMMARY
          echo "[Lighthouse Report]($report_url)" >> $GITHUB_STEP_SUMMARY

      - name: Set Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: lighthouse
          LABEL: "LightHouse Score"
          STATUS: ${{ steps.score.outputs.result }}
          COLOR: 212121
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
