name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3
        id: pages_conf
        with:
          enablement: true
          token: ${{ secrets.GH_PAT }}

      - name: Audit Resume using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        id: lighthouse
        with:
          urls: ${{ steps.pages_conf.outputs.base_url }}/
          temporaryPublicStorage: true
          runs: 1

      - name: Calculate total score
        id: score
        run: |
          performance=$(python -c 'import json; data = json.loads(\'${{ steps.lighthouse.outputs.manifest }}\'); print(data[0]["summary"]["performance"])')
          echo "{total}={$performance}" >> $GITHUB_OUTPUT

      - name: Set Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: lighthouse
          LABEL: "LightHouse Score"
          STATUS: ${{ steps.score.total }}
          COLOR: AAAAAA
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
